version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  customers:
    image: ${DOCKER_REGISTRY}customers
    build:
      context: .
      dockerfile: src/Customers/Dockerfile

  fakebt:
    image: ${DOCKER_REGISTRY}fakebt
    build:
      context: .
      dockerfile: src/FakeBt/Dockerfile


  phonelineorderer:
    image: ${DOCKER_REGISTRY}phonelineorderer
    build:
      context: .
      dockerfile: src/PhoneLineOrderer/Dockerfile


  phonelineorderer.ordersplacedsubscriber:
    image: ${DOCKER_REGISTRY}phonelineordererordersplacedsubscriber
    build:
      context: .
      dockerfile: src/PhoneLineOrders.OrdersPlacedSubscriber/Dockerfile


  customers.phonelineordercompletedsubscriber:
    image: ${DOCKER_REGISTRY}customersphonelineordercompletedsubscriber
    build:
      context: .
      dockerfile: src/Customers.PhoneLineOrderCompletedSubscriber/Dockerfile


  fakebt.orderupdater:
    image: ${DOCKER_REGISTRY}fakebtorderupdater
    build:
      context: .
      dockerfile: src/FakeBt.OrderUpdater/Dockerfile


  smssender.subscribers:
    image: ${DOCKER_REGISTRY}smssendersubscribers
    build:
      context: .
      dockerfile: src/SmsSender.Subscribers/Dockerfile

