version: '3.4'

services:
  sql.data:
      environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
      ports:
        - "5433:1433"    # Important: In a production environment your should remove the external port
 
  customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=sa;Password=Pass@word
      #- ConnectionString=${CUSTOMERS_DB:-Server=sql.da3ta;Initial Catalog=Microservices;User Id=sa;Password=Pass@word}
      - EventStoreUrl=tcp://admin:changeit@eventstore:1113
    ports:
      - "5001:80"

  eventstore:
    ports:
      - "1113:1113"
      - "2113:2113"

  phonelineorderer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=sa;Password=Pass@word
      - CustomersWebServiceUrl=customers
    ports:
      - "5002:80"
 
  phonelineorderer.ordersplacedsubscriber:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=sa;Password=Pass@word
      - CustomersWebServiceUrl=http://customers
      - FakeBtWebServiceUrl=http://fakebt

  customers.phonelineordercompletedsubscriber:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=sa;Password=Pass@word  
      - PhoneLineOrdererServiceUrl=http://phonelineorderer
  
  smssender:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=sa;Password=Pass@word  
    ports:
      - "5004:80"

  smssender.subscribers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=sa;Password=Pass@word
      - CustomersMicroserviceUrl=http://customers
      - PhoneLineOrdererMicroserviceUrl=http://phonelineorderer

  fakebt:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=sa;Password=Pass@word
      - PhoneLineOrdererWebServiceUrl=http://phonelineorderer
    ports:
      - "5003:80"

  fakebt.orderupdater:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=sa;Password=Pass@word
      - PhoneLineOrdererWebServiceUrl=http://phonelineorderer
