version: '3.4'

services:
  eventstore:
    ports:
      - "1113:1113"
      - "2113:2113"

  sql.data:
      environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
      ports:
        - "5433:1433"    # Important: In a production environment your should remove the external port
 
  customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=CustomersMicroservice;Password=Customers@123
      #- ConnectionString=${CUSTOMERS_DB:-Server=sql.da3ta;Initial Catalog=Microservices;User Id=sa;Password=Pass@word}
    ports:
      - "5001:80"

  customers.phonelineordercompletedsubscriber:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=CustomersMicroservice;Password=Customers@123
      - PhoneLineOrdererServiceUrl=http://phonelineorderer

  phonelineorderer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=PhoneLineOrdererMicroservice;Password=PhoneLineOrderer@456
      - CustomersWebServiceUrl=http://customers
    ports:
      - "5002:80"
 
  phonelineorderer.ordersplacedsubscriber:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=PhoneLineOrdererMicroservice;Password=PhoneLineOrderer@456
      - CustomersWebServiceUrl=http://customers
      - FakeBtWebServiceUrl=http://fakebt

  smssender:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=SmsSenderMicroservice;Password=SmsSender@012
    ports:
      - "5004:80"

  smssender.subscribers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=SmsSenderMicroservice;Password=SmsSender@012
      - CustomersMicroserviceUrl=http://customers
      - PhoneLineOrdererMicroserviceUrl=http://phonelineorderer

  fakebt:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=FakeBtMicroservice;Password=FakeBtMicroservice@789
      - PhoneLineOrdererWebServiceUrl=http://phonelineorderer
    ports:
      - "5003:80"

  fakebt.orderupdater:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data,1433;Initial Catalog=Microservices;User Id=FakeBtMicroservice;Password=FakeBtMicroservice@789
      - PhoneLineOrdererWebServiceUrl=http://phonelineorderer
